=== TerribleTurtle/spellcasters-community-api/schemas/v1/consumable.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Consumable",
  "description": "Loot items found in chests or dropped by enemies.",
  "type": "object",
  "required": [
    "game_version",
    "consumable_id",
    "name",
    "effect_type",
    "value",
    "ttl",
    "last_modified"
  ],
  "properties": {
    "$schema": { "type": "string" },
    "game_version": {
      "type": "string"
    },
    "last_modified": { "type": "string", "format": "date-time", "description": "UTC Timestamp of the last update" },
    "consumable_id": {
      "type": "string",
      "description": "Unique ID (e.g., 'small_health_potion')."
    },
    "name": {
      "type": "string"
    },
    "image_required": {
      "type": "boolean",
      "default": true
    },
    "effect_type": {
      "type": "string",
      "enum": ["Heal", "Charge_Refill", "Buff"],
      "description": "The mechanic triggered on pickup/use."
    },
    "value": {
      "type": "integer",
      "description": "Magnitude of the effect (e.g., 50 HP)."
    },
    "ttl": {
      "type": "integer",
      "minimum": 0,
      "description": "Time-To-Live in seconds before the item despawns from the world."
    }
  },
  "additionalProperties": false
}

=== TerribleTurtle/spellcasters-community-api/api/v1/consumables.json
[
  {
    "$schema": "../../schemas/v1/consumable.schema.json",
    "game_version": "0.0.1",
    "consumable_id": "light_heal",
    "name": "Light Heal",
    "effect_type": "Heal",
    "value": 25,
    "ttl": 30,
    "last_modified": "2026-02-04T15:27:05.217337Z"
  },
  {
    "$schema": "../../schemas/v1/consumable.schema.json",
    "game_version": "0.0.1",
    "consumable_id": "medium_heal",
    "name": "Medium Heal",
    "effect_type": "Heal",
    "value": 50,
    "ttl": 30,
    "last_modified": "2026-02-04T15:27:05.217803Z"
  },
  {
    "$schema": "../../schemas/v1/consumable.schema.json",
    "game_version": "0.0.1",
    "consumable_id": "medium_recharge",
    "name": "Medium Recharge",
    "effect_type": "Charge_Refill",
    "value": 50,
    "ttl": 30,
    "last_modified": "2026-02-04T15:27:05.217979Z"
  },
  {
    "$schema": "../../schemas/v1/consumable.schema.json",
    "game_version": "0.0.1",
    "consumable_id": "small_recharge",
    "name": "Small Recharge",
    "effect_type": "Charge_Refill",
    "value": 25,
    "ttl": 30,
    "last_modified": "2026-02-05T03:28:27.274024Z"
  }
]
